com.atomikos.icatch.log_base_dir=./atomikos-logs
com.atomikos.icatch.tm_unique_name=xa-poc-tm
com.atomikos.icatch.max_timeout=60000
com.atomikos.icatch.default_jta_timeout=30000
com.atomikos.icatch.max_actives=200
